config/routes.rb
Itbs::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :timesheets,  except: [:new, :create]

  namespace :admin do
    resources :employees
    resources :types, :projects
  end

  root :to => 'timesheets#index'

end

app/controllers/admin/types_controller.rb
class Admin::TypesController < ApplicationController
  # GET /admin/types
  # GET /admin/types.json
  def index
    @types = Type.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @types }
    end
  end

  # GET /admin/types/1
  # GET /admin/types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type }
    end
  end

  # GET /admin/types/new
  # GET /admin/types/new.json
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
    end
  end

  # GET /admin/types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /admin/types
  # POST /admin/types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to admin_type_path(@type), notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/types/1
  # PUT /admin/types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to admin_type_path(@type), notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to admin_types_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.json
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @types }
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/types_helper.rb
module Admin::TypesHelper
end

app/views/admin/types/_form.html.erb
<%= form_for [:admin, @type] do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/types/edit.html.erb
<h1>Editing admin_type</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_type_path(@type) %> |
<%= link_to 'Back', admin_types_path %>

app/views/admin/types/index.html.erb
<h1>Listing admin_types</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th></th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td><%= type.code %></td>
    <td><%= type.name %></td>
    <td><%= link_to 'Show', admin_type_path(type) %></td>
    <td><%= link_to 'Edit', edit_admin_type_path(type) %></td>
    <td><%= link_to 'Destroy', admin_type_path(type), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Type', new_admin_type_path %>

app/views/admin/types/new.html.erb
<h1>New admin_type</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_types_path %>

app/views/admin/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @type.code %>
</p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>


<%= link_to 'Edit', edit_admin_type_path(@type) %> |
<%= link_to 'Back', admin_types_path %>