config/routes.rb
Itbs::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :timesheets,  except: [:new, :create]

  namespace :admin do
    resources :employees
    resources :types, :projects
  end

  root :to => 'timesheets#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :employee_number, :jira_username, :tempo_staff_id, :email, :password, :password_comfirmation

  validates :employee_number, :tempo_staff_id, :presence => true

  validates :jira_username, :presence => true, :uniqueness => true

  has_many :timesheets

  has_secure_password

  before_destroy :ensure_not_referenced_by_any_timesheet

  private

    def ensure_not_referenced_by_any_timesheet
        if timesheets.empty?
          return true
        else
          errors.add(:base, 'This employee is still linked to a timesheet')
          return false
        end
    end

end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
  # GET /admin/employees
  # GET /admin/employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /admin/employees/1
  # GET /admin/employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /admin/employees/new
  # GET /admin/employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /admin/employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /admin/employees
  # POST /admin/employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to admin_employee_path(@employee), notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/employees/1
  # PUT /admin/employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to admin_employee_path(@employee), notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/employees/1
  # DELETE /admin/employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to admin_employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/views/admin/employees/_form.html.erb
<%= form_for [:admin, @employee] do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this admin_employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :jira_username %><br />
    <%= f.text_field :jira_username %>
  </div>
  <div class="field">
    <%= f.label :tempo_staff_id %><br />
    <%= f.text_field :tempo_staff_id %>
  </div>
  <div class="field">
    <%= f.label :employee_number %><br />
    <%= f.text_field :employee_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password' %><br />
    <%= f.password_field :password, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, 'Confirmation' %><br />
    <%= f.password_field :password, size: 40 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/employees/edit.html.erb
<h1>Editing admin_employee</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_employee_path(@employee)%> |
<%= link_to 'Back', admin_employees_path %>

app/views/admin/employees/index.html.erb
<h1>Listing admin_employees</h1>

<table>
  <tr>
    <th>Jira username</th>
    <th>Tempo staff</th>
    <th>Number</th>
    <th>Employee number</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.jira_username %></td>
    <td><%= employee.tempo_staff_id %></td>
    <td><%= employee.employee_number %></td>
    <td><%= employee.employee_number %></td>
    <td><%= employee.email %></td>
    <td><%= link_to 'Show', admin_employee_path(employee) %></td>
    <td><%= link_to 'Edit', edit_admin_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', admin_employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_admin_employee_path %>

app/views/admin/employees/new.html.erb
<h1>New admin_employee</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_employees_path %>

app/views/admin/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Jira username:</b>
  <%= @employee.jira_username %>
</p>

<p>
  <b>Tempo staff:</b>
  <%= @employee.tempo_staff_id %>
</p>

<p>
  <b>Employee number:</b>
  <%= @employee.employee_number %>
</p>

<p>
  <b>Email:</b>
  <%= @employee.email %>
</p>


<%= link_to 'Edit', edit_admin_employee_path(@employee) %> |
<%= link_to 'Back', admin_employees_path %>