config/routes.rb
Itbs::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :timesheets,  except: [:new, :create]

  namespace :admin do
    resources :employees
    resources :types, :projects
  end

  root :to => 'timesheets#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :code, :name

  validates :code, :name, :presence => true

  validates :code, :length => {:is=>6}

  has_many :worklogs

  before_destroy :ensure_not_referenced_by_any_worklog

  private

    def ensure_not_referenced_by_any_worklog
        if worklogs.empty?
          return true
        else
          errors.add(:base, 'Referenced by worklogs')
          return false
        end
    end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  # GET /admin/projects
  # GET /admin/projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /admin/projects/new
  # GET /admin/projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /admin/projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to admin_project_path(@project), notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/projects/1
  # PUT /admin/projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to admin_project_path(@project), notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to admin_projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project] do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this admin_project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :code %><br />
      <%= f.text_field :code %>
    </div>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<h1>Editing admin_project</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_project_path(@project) %> |
<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/index.html.erb
<h1>Listing admin_projects</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.code %></td>
    <td><%= project.name %></td>
    <td><%= link_to 'Show', admin_project_path(project) %></td>
    <td><%= link_to 'Edit', edit_admin_project_path(project) %></td>
    <td><%= link_to 'Destroy', admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_admin_project_path %>

app/views/admin/projects/new.html.erb
<h1>New admin_project</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @project.code %>
</p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_admin_project_path(@project) %> |
<%= link_to 'Back', admin_projects_path %>