config/routes.rb
Itbs::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :timesheets,  except: [:new, :create]

  namespace :admin do
    resources :employees
    resources :types, :projects
  end

  root :to => 'timesheets#index'

end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  attr_accessible :end_date, :employee, :worklogs, :worklogs_attributes

  has_many :worklogs, :dependent => :destroy
  belongs_to :employee

  validates :end_date, :employee, :presence => true
  validates_associated :worklogs

  accepts_nested_attributes_for :worklogs, :allow_destroy => true

end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  # GET /timesheets
  # GET /timesheets.json
  def index
    @timesheets = Timesheet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timesheets }
    end
  end

  # GET /timesheets/1
  # GET /timesheets/1.json
  def show
    @timesheet = Timesheet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timesheet }
    end
  end

  # GET /timesheets/1/edit
  def edit
    @timesheet = Timesheet.find(params[:id])
  end

  # PUT /timesheets/1
  # PUT /timesheets/1.json
  def update
    @timesheet = Timesheet.find(params[:id])

    respond_to do |format|
      if @timesheet.update_attributes(params[:timesheet])
        format.html { redirect_to @timesheet, notice: 'Timesheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/timesheets/_form.html.erb
<%= form_for(@timesheet) do |f| %>

    <%= f.fields_for :worklogs do |builder| %>

        <% if builder.object.errors.any? %>
            <div id="error_explanation">
                <ul>
                    <% builder.object.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <%= render 'worklog_fields', :f => builder %>
    <% end %>
    <p><%= link_to_add_fields "Add Worklog", f, :worklogs %></p>
    <p><%= f.submit "Submit" %></p>
<% end %>

app/views/timesheets/_worklog_fields.html.erb
<p class="fields">
        <%= f.date_select(:date) %>
        <%= f.collection_select(:project_id, Project.all, :id, :name ) %>
        <%= f.collection_select(:type_id, Type.all, :id, :name ) %>
        <%= f.text_field(:value, :size => "2" ) %>
        <%= f.text_field(:description) %>
        <%= f.hidden_field :_destroy %>
        <%= link_to_remove_fields "remove", f %>
</p>

app/views/timesheets/edit.html.erb
<h1>Editing timesheet</h1>

<% if @timesheet.errors.any? %>
    <div id="error_explanation">
        <ul>
            <% @timesheet.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

Employee: <%= @timesheet.employee.jira_username %><br>
End Date: <%= @timesheet.end_date %><br>

<%= render :partial => 'form' %>

<p>
<%= link_to 'Show', @timesheet %> |
<%= link_to 'Back', timesheets_path %>

app/views/timesheets/index.html.erb
<h1>Listing timesheets</h1>

<table>
  <tr>
    <th>End Date</th>
    <th>Employee</th>
    <th></th>
  </tr>

<% @timesheets.each do |timesheet| %>
  <tr>
    <td><%= timesheet.end_date %></td>
    <td><%= timesheet.employee.jira_username %></td>
    <td><%= link_to 'Show', timesheet_path(timesheet) %></td>
    <td><%= link_to 'Edit', edit_timesheet_path(timesheet) %></td>
    <td><%= link_to 'Destroy', timesheet_path(timesheet), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/timesheets/show.html.erb
<p id="notice"><%= notice %></p>

Employe:<%= @timesheet.employee.jira_username %><br>
End Date:<%= @timesheet.end_date %>

<table>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @timesheet.worklogs.each do | worklog |%>
    <tr>
        <td><%= worklog.date %></td>
        <td><%= worklog.project.name %></td>
        <td><%= worklog.type.name %></td>
        <td><%= worklog.value %></td>
        <td><%= worklog.description %></td>
    </tr>
    <% end %>
</table>


</p>
<%= link_to 'Edit', edit_timesheet_path(@timesheet) %> |
<%= link_to 'Back', timesheets_path %>